version: '3.8'

services:
  web:
    image: roicy/socialaws:latest
    container_name: django_app
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=social_media_feed.settings

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - static_volume:/usr/src/app/static
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

volumes:
  static_volume:
