version: '3'

services:
  web:
    image: your_dockerhub_username/your_django_app:latest
    command: gunicorn social_media_feed.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: roicy
      POSTGRES_PASSWORD: 2910
      POSTGRES_DB: social_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: