version: '3.11'

services:
  db:
    image: postgres:13
    container_name: social_media_db
    environment:
      POSTGRES_DB: social_db
      POSTGRES_USER: roicy
      POSTGRES_PASSWORD: 2910
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  web:
    build: .
    container_name: django_app
    command: gunicorn --bind 0.0.0.0:8000 social_media_feed.wsgi:application
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DJANGO_DB_HOST=db
      - DJANGO_DB_NAME=social_db
      - DJANGO_DB_USER=roicy
      - DJANGO_DB_PASSWORD=2910
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge

